# Generated by Django 5.1 on 2024-08-20 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='players',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='player_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
