# Generated by Django 5.1 on 2024-08-21 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_players_alter_game_player_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='player_name',
            new_name='player',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='players',
            new_name='table',
        ),
    ]
