# Generated by Django 5.1 on 2024-08-21 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_rename_player_name_game_player_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='dice_per_player',
            field=models.IntegerField(null=True),
        ),
    ]
