# Generated by Django 5.1 on 2024-08-21 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_game_dice_per_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='sides_per_die',
            field=models.IntegerField(null=True),
        ),
    ]
