# Generated by Django 5.1 on 2024-10-21 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_game_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
